### ISSUE TITLE
Creacion Modulo GastosLayout

### ISSUE THREAD

**Issue by fmramila** [fmramila/TADGroup7#8]
Una vez selecciones un evento, se mostrarán los datos del evento y permitira añadir usuarios y gastos al evento.

**Comment by fmramila** [comment]
Botones como añadir gastos, añadir usuario,  eliminar gasto, actualizar gasto, eliminar usuario seran necesarios en esta pantalla.

**Comment by sorul** [comment]
@fmramila Creo que este módulo sobra en el sidemenu. Desde EventoLayout se podrá acceder a los pagos de cada evento.

**Comment by naiaralandeta** [comment]
yo también estoy de acuerdo, vamos a quitarlo
